In [1]:
import random
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
initial_state= 0
alpha_size_param= 0.5
GAMMA= 0.9
EPS = 0.5
TRAIN_EPISODES = 200 
epsilon=0.5

In [3]:
'''obs0=current state
action= next state
obs1= next state
action: choosen action by random or best Q
'''
def Q_learning(table, obs0, obs1, reward_table, action):
    # Take the best value reachable from the state obs1
    best_value, _ = best_action_value(Q_table, obs1)

    # Calculate Q-target value 
    Q_target = reward_table[obs0, action] + GAMMA * best_value

    # Update Q(obs0,action)
    q_val=(1-alpha_size_param) * Q_table[obs0,action] + alpha_size_param * Q_target
    print('new Q value at',obs0,action,'is:',q_val)
    Q_table[obs0,action] = q_val
    #print('updated Q_table',Q_table)

In [ ]:
### these are for selecting next states
def select_eps_greedy_action(table, obs, n_actions):
    '''
    Select the action using a ε-greedy policy (add a randomness ε for the choice of the action)
    '''
    value, action = best_action_value(table, obs)
    print('Q_table', Q_table)
    random_flip=select_uniform_action()
    print('random flip result',random_flip)
    #if 1, choose best, else flip coin: choose 1 if 1 and 0 if 0
    if random_flip:
        print('is true. Select best. if tie, arbitrarily broken', action)
        return action
    else:
        flip_again=select_uniform_action()
        print('is false. Flip coin and select whichever shows up.',flip_again)
        return(flip_again)
            
def select_greedy_action(table, obs, n_actions):
    '''
    Select the action using a greedy policy (take the best action according to the policy)
    '''
    best_action = 0
    max_value = 0
    print('is there a tie? ',table[obs, 0] == table[obs, 1])
    #if tie, move
    if(table[obs, 0] == table[obs, 1]):
        if(obs==0):
            best_action = 1
        else:
            best_action = 0
        max_value = table[obs, best_action]
    #else, choose best
    else:
        for i,action in enumerate(n_actions):
            if table[obs, action] > max_value:
                best_action = action
                max_value = table[obs, action]
        print('no tie. Be greedy.Best is q and state ',max_value, best_action, 'from ',table)       
    value, action = max_value, best_action
    return action

def select_uniform_action():
 #obs = current state  
    return np.random.randint(2)
    

def best_action_value(table, state):
    '''
    Exploring the table, take the best action that maximize Q(s,a)
    '''
    best_action = 0
    max_value = 0
    for i,action in enumerate(n_actions):        
        if table[state, action] > max_value:
            best_action = action
            max_value = table[state, action]
    return max_value, best_action

### Q1

In [49]:
reward_table= np.array([[1,0],[0,1]])
Q_table=np.array([[0,0],[0,0]],dtype='float32')

print('initial Q',Q_table)
n_actions= [0,1]
current_state = initial_state

for i in range(200):
    print('round:',i)
    # Select the action following uniform random policy
    action = select_uniform_action()
    print('Transition:',current_state,'->',action)
    Q_learning(Q_table,current_state,action,reward_table,action)
    #update current to next state
    current_state = action
    print('Q table at ',i,'th step:')
    print(Q_table)
    print('----------')
    

initial Q [[0. 0.]
 [0. 0.]]
round: 0
Transition: 0 -> 0
new Q value at 0 0 is: 0.5
Q table at  0 th step:
[[0.5 0. ]
 [0.  0. ]]
----------
round: 1
Transition: 0 -> 0
new Q value at 0 0 is: 0.975
Q table at  1 th step:
[[0.975 0.   ]
 [0.    0.   ]]
----------
round: 2
Transition: 0 -> 0
new Q value at 0 0 is: 1.426250022649765
Q table at  2 th step:
[[1.42625 0.     ]
 [0.      0.     ]]
----------
round: 3
Transition: 0 -> 0
new Q value at 0 0 is: 1.854937481880188
Q table at  3 th step:
[[1.8549374 0.       ]
 [0.        0.       ]]
----------
round: 4
Transition: 0 -> 1
new Q value at 0 1 is: 0.0
Q table at  4 th step:
[[1.8549374 0.       ]
 [0.        0.       ]]
----------
round: 5
Transition: 1 -> 0
new Q value at 1 0 is: 0.8347218453884125
Q table at  5 th step:
[[1.8549374  0.        ]
 [0.83472186 0.        ]]
----------
round: 6
Transition: 0 -> 1
new Q value at 0 1 is: 0.37562483847141265
Q table at  6 th step:
[[1.8549374  0.37562484]
 [0.83472186 0.        ]]
---------

Transition: 1 -> 0
new Q value at 1 0 is: 6.414793419837952
Q table at  91 th step:
[[7.235328  5.88634  ]
 [6.4147935 6.870046 ]]
----------
round: 92
Transition: 0 -> 1
new Q value at 0 1 is: 6.0346908330917355
Q table at  92 th step:
[[7.235328  6.034691 ]
 [6.4147935 6.870046 ]]
----------
round: 93
Transition: 1 -> 0
new Q value at 1 0 is: 6.463294434547425
Q table at  93 th step:
[[7.235328  6.034691 ]
 [6.4632945 6.870046 ]]
----------
round: 94
Transition: 0 -> 0
new Q value at 0 0 is: 7.373561787605286
Q table at  94 th step:
[[7.373562  6.034691 ]
 [6.4632945 6.870046 ]]
----------
round: 95
Transition: 0 -> 0
new Q value at 0 0 is: 7.504883766174316
Q table at  95 th step:
[[7.504884  6.034691 ]
 [6.4632945 6.870046 ]]
----------
round: 96
Transition: 0 -> 0
new Q value at 0 0 is: 7.629639577865601
Q table at  96 th step:
[[7.6296396 6.034691 ]
 [6.4632945 6.870046 ]]
----------
round: 97
Transition: 0 -> 1
new Q value at 0 1 is: 6.108866190910339
Q table at  97 th step:
[[7

round: 168
Transition: 1 -> 1
new Q value at 1 1 is: 8.991579008102416
Q table at  168 th step:
[[8.901834  7.8688965]
 [7.9753656 8.991579 ]]
----------
round: 169
Transition: 1 -> 0
new Q value at 1 0 is: 7.99350790977478
Q table at  169 th step:
[[8.901834  7.8688965]
 [7.993508  8.991579 ]]
----------
round: 170
Transition: 0 -> 0
new Q value at 0 0 is: 8.956741857528687
Q table at  170 th step:
[[8.956742  7.8688965]
 [7.993508  8.991579 ]]
----------
round: 171
Transition: 0 -> 1
new Q value at 0 1 is: 7.98065881729126
Q table at  171 th step:
[[8.956742 7.980659]
 [7.993508 8.991579]]
----------
round: 172
Transition: 1 -> 1
new Q value at 1 1 is: 9.042000102996827
Q table at  172 th step:
[[8.956742 7.980659]
 [7.993508 9.042   ]]
----------
round: 173
Transition: 1 -> 0
new Q value at 1 0 is: 8.02728796005249
Q table at  173 th step:
[[8.956742 7.980659]
 [8.027288 9.042   ]]
----------
round: 174
Transition: 0 -> 0
new Q value at 0 0 is: 9.008905172348022
Q table at  174 th s

### Q2

In [50]:

reward_table= np.array([[1,0],[0,1]])
Q_table=np.array([[0,0],[0,0]],dtype='float32')

print('initial Q',Q_table)
n_actions= [0,1]
current_state = initial_state

for i in range(200):
    print('round:',i)
    # Select the action following uniform random policy
    action = select_eps_greedy_action(Q_table, current_state, n_actions)
    print('Transition:',current_state,'->',action)
    Q_learning(Q_table,current_state,action,reward_table,action)
    #update current to next state
    current_state = action
    print('Q table at ',i,'th step:')
    print(Q_table)
    print('----------')

initial Q [[0. 0.]
 [0. 0.]]
round: 0
Q_table [[0. 0.]
 [0. 0.]]
random flip result 0
is false. Flip coin and select whichever shows up. 1
Transition: 0 -> 1
new Q value at 0 1 is: 0.0
Q table at  0 th step:
[[0. 0.]
 [0. 0.]]
----------
round: 1
Q_table [[0. 0.]
 [0. 0.]]
random flip result 0
is false. Flip coin and select whichever shows up. 1
Transition: 1 -> 1
new Q value at 1 1 is: 0.5
Q table at  1 th step:
[[0.  0. ]
 [0.  0.5]]
----------
round: 2
Q_table [[0.  0. ]
 [0.  0.5]]
random flip result 0
is false. Flip coin and select whichever shows up. 0
Transition: 1 -> 0
new Q value at 1 0 is: 0.0
Q table at  2 th step:
[[0.  0. ]
 [0.  0.5]]
----------
round: 3
Q_table [[0.  0. ]
 [0.  0.5]]
random flip result 0
is false. Flip coin and select whichever shows up. 1
Transition: 0 -> 1
new Q value at 0 1 is: 0.225
Q table at  3 th step:
[[0.    0.225]
 [0.    0.5  ]]
----------
round: 4
Q_table [[0.    0.225]
 [0.    0.5  ]]
random flip result 0
is false. Flip coin and select which

Transition: 0 -> 0
new Q value at 0 0 is: 6.719898629188538
Q table at  60 th step:
[[6.7198987 5.5863986]
 [4.809271  7.496559 ]]
----------
round: 61
Q_table [[6.7198987 5.5863986]
 [4.809271  7.496559 ]]
random flip result 0
is false. Flip coin and select whichever shows up. 0
Transition: 0 -> 0
new Q value at 0 0 is: 6.883903765678406
Q table at  61 th step:
[[6.883904  5.5863986]
 [4.809271  7.496559 ]]
----------
round: 62
Q_table [[6.883904  5.5863986]
 [4.809271  7.496559 ]]
random flip result 0
is false. Flip coin and select whichever shows up. 1
Transition: 0 -> 1
new Q value at 0 1 is: 6.166650915145874
Q table at  62 th step:
[[6.883904 6.166651]
 [4.809271 7.496559]]
----------
round: 63
Q_table [[6.883904 6.166651]
 [4.809271 7.496559]]
random flip result 0
is false. Flip coin and select whichever shows up. 1
Transition: 1 -> 1
new Q value at 1 1 is: 7.621731185913086
Q table at  63 th step:
[[6.883904  6.166651 ]
 [4.809271  7.6217313]]
----------
round: 64
Q_table [[6.8

Q table at  115 th step:
[[9.364607  7.4410157]
 [7.990267  8.647242 ]]
----------
round: 116
Q_table [[9.364607  7.4410157]
 [7.990267  8.647242 ]]
random flip result 0
is false. Flip coin and select whichever shows up. 1
Transition: 1 -> 1
new Q value at 1 1 is: 8.714879512786865
Q table at  116 th step:
[[9.364607  7.4410157]
 [7.990267  8.71488  ]]
----------
round: 117
Q_table [[9.364607  7.4410157]
 [7.990267  8.71488  ]]
random flip result 0
is false. Flip coin and select whichever shows up. 1
Transition: 1 -> 1
new Q value at 1 1 is: 8.779135990142823
Q table at  117 th step:
[[9.364607  7.4410157]
 [7.990267  8.779136 ]]
----------
round: 118
Q_table [[9.364607  7.4410157]
 [7.990267  8.779136 ]]
random flip result 0
is false. Flip coin and select whichever shows up. 1
Transition: 1 -> 1
new Q value at 1 1 is: 8.8401789188385
Q table at  118 th step:
[[9.364607  7.4410157]
 [7.990267  8.8401785]]
----------
round: 119
Q_table [[9.364607  7.4410157]
 [7.990267  8.8401785]]
rand

new Q value at 1 0 is: 8.627022409439087
Q table at  171 th step:
[[9.619567 8.658178]
 [8.627023 9.751058]]
----------
round: 172
Q_table [[9.619567 8.658178]
 [8.627023 9.751058]]
random flip result 0
is false. Flip coin and select whichever shows up. 1
Transition: 0 -> 1
new Q value at 0 1 is: 8.71706509590149
Q table at  172 th step:
[[9.619567 8.717065]
 [8.627023 9.751058]]
----------
round: 173
Q_table [[9.619567 8.717065]
 [8.627023 9.751058]]
random flip result 1
is true. Select best. if tie, arbitrarily broken 1
Transition: 1 -> 1
new Q value at 1 1 is: 9.76350474357605
Q table at  173 th step:
[[9.619567 8.717065]
 [8.627023 9.763505]]
----------
round: 174
Q_table [[9.619567 8.717065]
 [8.627023 9.763505]]
random flip result 1
is true. Select best. if tie, arbitrarily broken 1
Transition: 1 -> 1
new Q value at 1 1 is: 9.775329732894898
Q table at  174 th step:
[[9.619567 8.717065]
 [8.627023 9.77533 ]]
----------
round: 175
Q_table [[9.619567 8.717065]
 [8.627023 9.77533 ]]

### Q3

In [51]:

reward_table= np.array([[1,0],[0,1]])
Q_table=np.array([[0,0],[0,0]],dtype='float32')

print('initial Q',Q_table)
n_actions= [0,1]
current_state = initial_state

for i in range(200):
    print('round:',i)
    # Select the action following greedy action policy
    action = select_greedy_action(Q_table, current_state, n_actions)
    print('Transition:',current_state,'->',action)
    Q_learning(Q_table,current_state,action,reward_table,action)
    #update current to next state
    current_state = action
    print('Q table at ',i,'th step:')
    print(Q_table)
    print('----------')

initial Q [[0. 0.]
 [0. 0.]]
round: 0
is there a tie?  True
Transition: 0 -> 1
new Q value at 0 1 is: 0.0
Q table at  0 th step:
[[0. 0.]
 [0. 0.]]
----------
round: 1
is there a tie?  True
Transition: 1 -> 0
new Q value at 1 0 is: 0.0
Q table at  1 th step:
[[0. 0.]
 [0. 0.]]
----------
round: 2
is there a tie?  True
Transition: 0 -> 1
new Q value at 0 1 is: 0.0
Q table at  2 th step:
[[0. 0.]
 [0. 0.]]
----------
round: 3
is there a tie?  True
Transition: 1 -> 0
new Q value at 1 0 is: 0.0
Q table at  3 th step:
[[0. 0.]
 [0. 0.]]
----------
round: 4
is there a tie?  True
Transition: 0 -> 1
new Q value at 0 1 is: 0.0
Q table at  4 th step:
[[0. 0.]
 [0. 0.]]
----------
round: 5
is there a tie?  True
Transition: 1 -> 0
new Q value at 1 0 is: 0.0
Q table at  5 th step:
[[0. 0.]
 [0. 0.]]
----------
round: 6
is there a tie?  True
Transition: 0 -> 1
new Q value at 0 1 is: 0.0
Q table at  6 th step:
[[0. 0.]
 [0. 0.]]
----------
round: 7
is there a tie?  True
Transition: 1 -> 0
new Q value

new Q value at 0 1 is: 0.0
Q table at  92 th step:
[[0. 0.]
 [0. 0.]]
----------
round: 93
is there a tie?  True
Transition: 1 -> 0
new Q value at 1 0 is: 0.0
Q table at  93 th step:
[[0. 0.]
 [0. 0.]]
----------
round: 94
is there a tie?  True
Transition: 0 -> 1
new Q value at 0 1 is: 0.0
Q table at  94 th step:
[[0. 0.]
 [0. 0.]]
----------
round: 95
is there a tie?  True
Transition: 1 -> 0
new Q value at 1 0 is: 0.0
Q table at  95 th step:
[[0. 0.]
 [0. 0.]]
----------
round: 96
is there a tie?  True
Transition: 0 -> 1
new Q value at 0 1 is: 0.0
Q table at  96 th step:
[[0. 0.]
 [0. 0.]]
----------
round: 97
is there a tie?  True
Transition: 1 -> 0
new Q value at 1 0 is: 0.0
Q table at  97 th step:
[[0. 0.]
 [0. 0.]]
----------
round: 98
is there a tie?  True
Transition: 0 -> 1
new Q value at 0 1 is: 0.0
Q table at  98 th step:
[[0. 0.]
 [0. 0.]]
----------
round: 99
is there a tie?  True
Transition: 1 -> 0
new Q value at 1 0 is: 0.0
Q table at  99 th step:
[[0. 0.]
 [0. 0.]]
------

new Q value at 0 1 is: 0.0
Q table at  174 th step:
[[0. 0.]
 [0. 0.]]
----------
round: 175
is there a tie?  True
Transition: 1 -> 0
new Q value at 1 0 is: 0.0
Q table at  175 th step:
[[0. 0.]
 [0. 0.]]
----------
round: 176
is there a tie?  True
Transition: 0 -> 1
new Q value at 0 1 is: 0.0
Q table at  176 th step:
[[0. 0.]
 [0. 0.]]
----------
round: 177
is there a tie?  True
Transition: 1 -> 0
new Q value at 1 0 is: 0.0
Q table at  177 th step:
[[0. 0.]
 [0. 0.]]
----------
round: 178
is there a tie?  True
Transition: 0 -> 1
new Q value at 0 1 is: 0.0
Q table at  178 th step:
[[0. 0.]
 [0. 0.]]
----------
round: 179
is there a tie?  True
Transition: 1 -> 0
new Q value at 1 0 is: 0.0
Q table at  179 th step:
[[0. 0.]
 [0. 0.]]
----------
round: 180
is there a tie?  True
Transition: 0 -> 1
new Q value at 0 1 is: 0.0
Q table at  180 th step:
[[0. 0.]
 [0. 0.]]
----------
round: 181
is there a tie?  True
Transition: 1 -> 0
new Q value at 1 0 is: 0.0
Q table at  181 th step:
[[0. 0.]
 